name: AdvancedAutoAnnounce
main: Kirtan\AdvancedAutoAnnounce\Main
version: 1.1.0
api: [5.0.0, 6.0.0]
author: Kirtan Vinayak
description: Automatically broadcast customizable server announcements without commands.